import './globals.css'
import { Inter } from 'next/font/google'
import Footer from './components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
        <html lang="en">
          {/* Place the styling to be inherited in here */}
          <body className={inter.className}>
            <div className='min-h-screen bg-gradient-to-br from-blue-500
          text- to-blue-300'>
                <main className='container'>
                  {children}
                </main>
                <Footer/>
            </div>
          </body>
        </html>
    
  )
}
